### ISSUE TITLE
Jest + Typescript + Ckeditor for Testing

### ISSUE THREAD

**Issue by michael-vasyliv** [ckeditor/ckeditor5-react#262]
Hello! Thank you for your work in this package. I've faced with an issue when I tried to test my components with `jest`, Here is my config:
```
const tsconfig = require('./tsconfig.json');

const { paths } = tsconfig.compilerOptions;
const moduleNameMapper = Object
    .keys(paths)
    .reduce((result, key) => {
        const value = paths[key][0];
        const nextKey = key.replace(/\*$/, '(.*)');
        const nextValue = value
            .replace(/^\./, '<rootDir>')
            .replace(/\*$/, '$1');

        return {
            ...result,
            [nextKey]: nextValue
        };
    }, {});

module.exports = {
    preset: 'ts-jest',
    coverageDirectory: '<rootDir>/coverage',
    coverageProvider: 'v8',
    coverageReporters: ['lcov'],
    roots: ['<rootDir>/tests/'],
    moduleNameMapper: {
        ...moduleNameMapper,
        '\\.(css|less|svg|scss)$': '<rootDir>/tests/__mocks__/style.js'
    },
    transform: {
        '^.+\\\\.(js|jsx|ts|tsx)$': 'ts-jest'
    },
    transformIgnorePatterns: [
        '<rootDir>.*(node_modules)(?!.*(ckeditor5-react|ckeditor5-build-classic|ckeditor5-build|ckeditor5-core|ckeditor5-highlight|ckeditor5-utils|ckeditor5-ui|lodash-es).*).js$'
    ],
    setupFilesAfterEnv: [
        '<rootDir>/tests/config.ts'
    ],
    testEnvironment: 'jsdom'
};

```

```
"@ckeditor/ckeditor5-autoformat": "^29.1.0",
        "@ckeditor/ckeditor5-basic-styles": "^29.1.0",
        "@ckeditor/ckeditor5-block-quote": "^29.1.0",
        "@ckeditor/ckeditor5-clipboard": "^29.1.0",
        "@ckeditor/ckeditor5-core": "^29.1.0",
        "@ckeditor/ckeditor5-dev-utils": "^25.4.1",
        "@ckeditor/ckeditor5-editor-classic": "^29.1.0",
        "@ckeditor/ckeditor5-engine": "^29.1.0",
        "@ckeditor/ckeditor5-essentials": "^29.1.0",
        "@ckeditor/ckeditor5-heading": "^29.1.0",
        "@ckeditor/ckeditor5-image": "^29.1.0",
        "@ckeditor/ckeditor5-indent": "^29.1.0",
        "@ckeditor/ckeditor5-link": "^29.1.0",
        "@ckeditor/ckeditor5-list": "^29.1.0",
        "@ckeditor/ckeditor5-paragraph": "^29.1.0",
        "@ckeditor/ckeditor5-paste-from-office": "^29.1.0",
        "@ckeditor/ckeditor5-react": "^3.0.2",
        "@ckeditor/ckeditor5-table": "^29.1.0",
        "@ckeditor/ckeditor5-theme-lark": "^29.1.0",
        "@ckeditor/ckeditor5-typing": "^29.1.0",
        "@ckeditor/ckeditor5-upload": "^29.1.0",
        "@ckeditor/ckeditor5-utils": "^29.1.0",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-popper": "^2.2.5",
        "react-redux": "^7.2.4",
        "react-router-dom": "^5.2.0",
        "react-transition-group": "^4.4.2",
        "babel-jest": "^27.1.0",
        "jest": "^27.1.0",
        "ts-jest": "^27.0.5",

```

Here is the error

```
npm run test

> jest --clearCache && NODE_OPTIONS=--experimental-vm-modules jest

Cleared /tmp/jest_rs
(node:69035) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  tests/components/text-editor/axios-upload-adapter.test1.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/michael/workspace/limsui/node_modules/@ckeditor/ckeditor5-core/src/index.js:10
    export { default as Plugin } from './plugin';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { Plugin } from '@ckeditor/ckeditor5-core';
        | ^
      2 | import FileRepository, { FileLoader } from '@ckeditor/ckeditor5-upload/src/filerepository';
      3 | import { AxiosUploadAdapter } from './axios-upload-adapter';
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1517:14)
      at Object.<anonymous> (src/components/text-editor/axios-upload-plugin.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.826 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lims@0.0.0 test: `jest --clearCache && NODE_OPTIONS=--experimental-vm-modules jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lims@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
```
Node 14.17.x
```

**Comment by michael-vasyliv** [comment]
to fix issue you have to use [ts-jest/presets/js-with-ts](https://kulshekhar.github.io/ts-jest/docs/getting-started/presets/#the-presets)
