### ISSUE TITLE
Multi-root demo crahes at initialization

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5-react#450]
As in the title. When trying to open the multiroot demo it crashes:
```js
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at editorwatchdog.js:172:25
    at async w2 (useMultiRootEditor.tsx:380:76) 
```

**Comment by DawidKossowski** [comment]
Updating the`vite` version probably fixed this issue.
