### ISSUE TITLE
Unable import components that include CKEditor plugins in Jest tests

### ISSUE THREAD

**Issue by tgfischer** [ckeditor/ckeditor5-react#66]
I'm trying to do a simple snapshot test of a component that includes CKEditor, and a plugin (in this case `@ckeditor/ckeditor5-highlight`). My component looks like this
```
import React from "react";
import PropTypes from "prop-types";
import CKEditor from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import Highlight from "@ckeditor/ckeditor5-highlight/src/highlight";

export const config = {
  extraPlugins: [Highlight],
  toolbar: [ ... ],
  heading: { .. .},
  highlight: {
    options: [ ... ]
  }
};

const Editor = ({ data, onChange }) => (
  <CKEditor
    editor={ClassicEditor}
    config={config}
    data={data}
    onChange={onChange}
  />
);

Editor.propTypes = {
  data: PropTypes.string,
  onChange: PropTypes.func.isRequired
};

Editor.defaultProps = {
  data: ""
};

export default Editor;
```

And my test looks like this

```
import React from "react";
import { shallow } from "enzyme";

import Editor from "../index";

describe("Editor tests", () => {
  const onChange = jest.fn();

  it("should render the component", () => {
    const wrapper = shallow(
      <Editor data="<p>Hello, World!</p>" onChange={onChange} />
    );
    expect(wrapper).toMatchSnapshot();
  });
});
```
When I run this test, I get the following error
```
$ yarn test Editor/__tests__/index.test
yarn run v1.13.0
$ npx jest --no-cache Editor/__tests__/index.test
 FAIL  app/src/components/Editor/__tests__/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /.../node_modules/@ckeditor/ckeditor5-highlight/src/highlight.js:10
    import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
    ^^^^^^

    SyntaxError: Unexpected token import

      3 | import CKEditor from "@ckeditor/ckeditor5-react";
      4 | import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
    > 5 | import Highlight from "@ckeditor/ckeditor5-highlight/src/highlight";
        | ^
      6 |
      7 | export const config = {
      8 |   extraPlugins: [Highlight],

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (app/src/components/Editor/index.js:5:1)
      at Object.<anonymous> (app/src/components/Editor/__tests__/index.test.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.811s
Ran all test suites matching /Editor\/__tests__\/index.test/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I tried out the suggested solution with `transformIgnorePatterns` like so
```
  ...
  transformIgnorePatterns: [
    "<rootDir>.*(node_modules)(?!.*(ckeditor5-core|ckeditor5-highlight|ckeditor5-utils|ckeditor5-ui|lodash-es).*).js$"
  ]
  ...
```
I came to that pattern by adding the packages that the compiler was complaining about, and rerunning the tests. But now the tests run out of memory trying to run the tests, presumably because it is compiling CKEditor before it runs the suite.
```
$ yarn test Editor/__tests__/index.test
yarn run v1.13.0
$ npx jest --no-cache Editor/__tests__/index.test

 RUNS  app/src/components/Editor/__tests__/index.test.js

<--- Last few GCs --->

[3374:0x2c0f740]   496466 ms: Mark-sweep 1481.6 (1563.5) -> 1481.6 (1532.5) MB, 1915.4 / 0.2 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1916 ms) last resort GC in old space requested
[3374:0x2c0f740]   498446 ms: Mark-sweep 1481.6 (1532.5) -> 1481.6 (1532.5) MB, 1980.2 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x10aa8a6258b9 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [/.../node_modules/@babel/core/lib/transformation/file/merge-map.js:~198] [pc=0x1d3fb787dae5](this=0x2d2516d822d1 <undefined>,item=0x3587f2ace161 <Object map = 0x21daa5042629>)
    2: arguments adaptor frame: 3->1
    3: map(this=0x2ca02ea7fd61 <JSArray[9132]>)
    4: /* anonymous */(aka /* anonymous */) [...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/bin/node]
 2: 0x8ccf9c [/usr/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/bin/node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
 7: 0x1d3fb74842fd

```
I also went through [this thread](https://github.com/facebook/jest/issues/4604), and tried out various solutions without success (e.g. renaming `.babelrc` to `babel.config.js`, different combinations of `transformIgnorePatterns`, extending `babel-jest`, etc)

If I do not include the plugin in the CKEditor, the test works as expected. How do you test components with Jest that include CKEditor plugins?

**Comment by pomek** [comment]
[You can't add to the existing build.](https://github.com/ckeditor/ckeditor5/issues/1047)

In the attached thread you will find a solution on how to create a custom build that will include a set of plugins that you can define. I am pretty sure that the mentioned error won't exist anymore.

**Comment by pomek** [comment]
Closing due to lack of activity.
